### ISSUE TITLE
Kubecost Namespace is not created

### ISSUE THREAD

**Issue by allamand** [aws-samples/eks-blueprints-add-ons#111]
When deploying the Kubecost Add-On with ArgoCD, it fails with the error : 

```
Failed sync attempt to 41eef70473f63b5564ffb953d47a9a70b4463cf4: one or more objects failed to apply, reason: namespaces "kubecost" not found (retried 1 times).
```

The Argo Application did not create the Kubecost namespace, so id can not be deployed automatically

**Comment by bryantbiggs** [comment]
closed in #112
