### ISSUE TITLE
Consistency on the addon naming in the app of app template

### ISSUE THREAD

**Issue by starchx** [aws-samples/eks-blueprints-add-ons#24]
We should have a consistent naming in the app of app templates, this allows upstream whoever consumes this repo to follow the same naming patterns for all addons. Examples:

For AWS Load Balancer Controller: 👍 
```
# chart/templates/aws-load-balancer-controller.yaml
{{- if and (.Values.awsLoadBalancerController) (.Values.awsLoadBalancerController.enable) -}}
```

For Appmesh Controller: 👎 
```
# chart/templates/appmesh-controller.yaml
{{- if and (.Values.appMesh) (.Values.appMesh.enable) -}}  ==> should be Values.appmeshController
```

Another minor one, but can we change `enable` to `enabled`? 

```
{{- if and (.Values.awsLoadBalancerController) (.Values.awsLoadBalancerController.enable) -}}
==>>
{{- if and (.Values.awsLoadBalancerController) (.Values.awsLoadBalancerController.enabled) -}}
```

I am working on getting SSP CDK to consume this repo (https://github.com/aws-quickstart/ssp-amazon-eks/pull/300). Any feedback on this are appreciated. While waiting, I will submit a PR for this.

**Comment by bryantbiggs** [comment]
I agree on the consistency point. However, I disagree on `enable` vs `enabled`. I believe `enable` is the more commonly used tense for this boolean action

**Comment by starchx** [comment]
> I agree on the consistency point. However, I disagree on `enable` vs `enabled`. I believe `enable` is the more commonly used tense for this boolean action

@bryantbiggs , Thanks for the feedback. Great that we agreed on the add on naming consistency.

I am happy to leave as `enable`, it is just many helm projects I have seen are all using `enabled` when it represents as a single word:

- https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
- https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml
- https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/values.yaml

If `enable` is still the favor, I will update my PR accordingly. Thanks.

**Comment by bryantbiggs** [comment]
I believe this is resolved by now
