### ISSUE TITLE
Tagging the repo

### ISSUE THREAD

**Issue by Aminkta** [aws-samples/eks-blueprints-add-ons#61]
Hello,

Not an issue actually. I'm just wondering if there's a reason this repo does not contain any tags. It would be very useful to be able to reference a specific tag in the eks blueprints terraform modules. Thanks.

**Comment by bryantbiggs** [comment]
This repo  is not intended to be used in place - its intended to be a starter for users to fork and modify to suite their needs. Therefore, a tag isn't necessary here
