### ISSUE TITLE
[Bug] repoURL harcoded in addons argocd applications

### ISSUE THREAD

**Issue by csantanapr** [aws-samples/eks-blueprints-add-ons#89]
repoURL: {{ .Values.repoUrl }} hardcoded 

currently hardcoded
```
spec:
  source:
    repoURL: https://github.com/aws-samples/eks-blueprints-add-ons
```
It should be
```
spec:
  source:
    repoURL: {{ .Values.repoUrl }}
```
Places where is hardcoded
https://github.com/aws-samples/eks-blueprints-add-ons/blob/main/chart/templates/argo-rollouts.yaml#L12
https://github.com/aws-samples/eks-blueprints-add-ons/blob/main/chart/templates/kube-state-metrics.yaml#L12
https://github.com/aws-samples/eks-blueprints-add-ons/blob/main/chart/templates/kubernetes-dashboard.yaml#L12

**Comment by bryantbiggs** [comment]
related #34
