### ISSUE TITLE
Unable to install kube-prometheus-stack

### ISSUE THREAD

**Issue by DylanWarnock** [aws-samples/eks-blueprints-add-ons#97]
Installing kube-prometheus-stack fails with the below error:

<img width="1168" alt="Screen Shot 2022-10-25 at 8 34 54 PM" src="https://user-images.githubusercontent.com/107946287/197928586-588cdaba-d85f-4504-9e33-b2244d32061b.png">

Does some other repo need to be added to argocd to get this install working?

**Comment by bryantbiggs** [comment]
Could you please use the provided issue template and supply the requested information to troubleshoot

**Comment by DylanWarnock** [comment]
No problem! Can you point me to the template? When I select create issue there isn't a template to fill out.

**Comment by DylanWarnock** [comment]
I found the following question regarding issues:

**A reproducible test case or series of steps** 
Bootstrap an eks cluster using terraform and manage add-on via argocd as describe on this page https://aws-ia.github.io/terraform-aws-eks-blueprints/add-ons/argocd/
**The version of our code being used** -> latest
**Any modifications you've made relevant to the bug** -> no modifications
**Anything unusual about your environment or deployment** -> Using the eks blueprint for Argocd installed via terraform. Argocd is being used to manage add-on by using the application definition in /charts and the helm repo references in /addons

**Comment by bryantbiggs** [comment]
when you create a new issue the template is already provided - it looks like you erased the template when you created the issue

**Comment by bryantbiggs** [comment]
apologies - looks like this project does not have the default templates

**Comment by DylanWarnock** [comment]
Do I need to enable prometheus in terraform to install the kube-prometheus-stack? See:
https://aws-ia.github.io/terraform-aws-eks-blueprints/add-ons/prometheus/

**Comment by DylanWarnock** [comment]
It seem like the crds aren't being installed correctly

**Comment by DylanWarnock** [comment]
I set skipCrd to false and then following some advice [here](https://github.com/argoproj/argo-cd/issues/8128) specifically:

`@PaulWen I have solved it for now by deploying the whole thing, waiting for it to fail and then clicking on the offending CRD and sync with replace. However, this is not a good solution, replace should not be used, it can be dangerous. It can cause issue (not in this case, but in DB deployment or something similar you can lose data)`

Seems like a stop gap solution though.
